#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';
require __DIR__.'/../src/MyCommand.php';

#use MyCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new MyCommand());
$application->run();
